version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo Installing dependencies...
      - curl -sSfL https://raw.githubusercontent.com/aquasecurity/trivy/main/install.sh | sh
      - curl -sSfL https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip -o sonar-scanner.zip
      - unzip sonar-scanner.zip
      - mv sonar-scanner-*/bin/sonar-scanner /usr/local/bin
  pre_build:
    commands:
      - echo Logging into ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
      - echo Setting environment variables...
      - export SONAR_HOST_URL=http://3.23.100.113
      - export EKS_CLUSTER_NAME=DevSecOps-Cluster
  build:
    commands:
      - echo Running SonarQube scan...
      - sonar-scanner -Dsonar.projectKey=your-project-key
      - echo Building the Docker image...
      - docker build -t $ECR_REPO_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - docker push $ECR_REPO_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo Running Trivy scan...
      - trivy image --format json --output trivy-report.json $ECR_REPO_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
  post_build:
    commands:
      - echo Build completed on `date`
