replicaCount: 1

image:
  repository: 162186035982.dkr.ecr.us-west-2.amazonaws.com/database-app-image
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5432

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 10Gi

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

