replicaCount: 2

image:
  repository: 162186035982.dkr.ecr.us-west-2.amazonaws.com/api-app-image
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8083

ingress:
  enabled: true
  className: ""
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: api.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}

