pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                script {
                    if (env.BRANCH_NAME == 'develop') {
                        echo 'Building for develop branch...'
                        sh 'docker build -t 162186035982.dkr.ecr.us-west-2.amazonaws.com/api-app-image:develop .'
                    } else if (env.BRANCH_NAME == 'master') {
                        echo 'Building for master branch...'
                        sh 'docker build -t 162186035982.dkr.ecr.us-west-2.amazonaws.com/api-app-image:latest .'
                    }
                }
            }
        }
        stage('Push') {
            steps {
                script {
                    if (env.BRANCH_NAME == 'develop') {
                        echo 'Pushing for develop branch...'
                        sh 'docker push 162186035982.dkr.ecr.us-west-2.amazonaws.com/api-app-image:develop'
                    } else if (env.BRANCH_NAME == 'master') {
                        echo 'Pushing for master branch...'
                        sh 'docker push 162186035982.dkr.ecr.us-west-2.amazonaws.com/api-app-image:latest'
                    }
                }
            }
        }
    }
}
